CREATE TABLE time (
    id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    id_time VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL,
    nometime VARCHAR(200) NOT NULL,
    nomequadra VARCHAR(200) NOT NULL,
    nometecnico VARCHAR(200) NOT NULL,
    formacao VARCHAR(200) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE jogador (
    id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    id_time VARCHAR(200) NOT NULL,
    jogador_1 VARCHAR(200) NOT NULL,
    jogador_2 VARCHAR(200) NOT NULL,
    jogador_3 VARCHAR(200) NOT NULL,
    jogador_4 VARCHAR(200) NOT NULL,
    jogador_5 VARCHAR(200) NOT NULL,
    jogador_6 VARCHAR(200) NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);    